baseURL = 'https://growingcode.studio/'
languageCode = 'en-us'
title = 'John Falcón [growing code] - Software Architect'
theme = "ananke"
copyright = "All rights reserved, John P Falcón"

[params]
  subtitle = '..'
  author = 'John Falcón'

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
