baseURL = 'https://growingcode.studio/'
languageCode = 'en-us'
title = 'John P Falc贸n [growing code] - Software Architect'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
copyright = "All rights reserved, John P Falc贸n"

[params]
  subtitle = 'Cloud Architect'
  author = 'John P Falc贸n'
  site_logo = 'https://endeavour-one.s3.us-west-2.amazonaws.com/assets/john-falcon-software-architect-optimized.png'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About John'
  title = "Who is John Falc贸n"
  url = '#about-john'
  weight = 100
[[menu.main]]
  identifier = 'work'
  name = 'Work'
  title = "Work by John"
  url = '#homepage-posts'
  weight = 110
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = "John's posts"
  url = '/posts/'
  weight = 120
[[menu.main]]
  identifier = 'contact'
  name = 'Quote'
  title = "Contact John"
  url = '/contact-john-falcon/'
  weight = 130

[deployment]
  [[deployment.targets]]
    name = "aws"
    URL = "s3://hugowebsitestack-hugowebsitebucket9c57a3f4-fvbkvhfnlgyc"
    region = "us-west-2"
    cloudFrontDistributionID = "E3I8WHJ362WR96"

  # Specify your file patterns to match for deployment
  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|html|svg|jpg|png|gif)$"
    cacheControl = "max-age=31536000, no-transform, public"

  [[deployment.matchers]]
    pattern = "^index\\.html$"
    cacheControl = "max-age=0, no-cache, no-store, must-revalidate"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']