name: Update site content

on:

  workflow_run:
    workflows: ["Deploy Infrastructure"]  # This triggers after the infra workflow
    types:
      - completed
      
  push:

    paths:
      - 'content/**'
      - 'layouts/**'
      - 'config.toml'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo --minify

  deploy:

    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy site with Hugo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
        run: |
          hugo deploy
          