name: Update site content

on:

  workflow_run:
    workflows: ["Deploy Infrastructure"]  # This triggers after the infra workflow
    types:
      - completed
      
  push:

    paths:
      - 'content/**'
      - 'layouts/**'
      - 'assets/**'
      - 'config.toml'
    paths-ignore:
      - 'infra/**'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      build-path: ${{ steps.build.outputs.build-path }}

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: | 
          hugo --minify
          echo "build-path=$(pwd)/public" >> $GITHUB_ENV  # Use environment variable instead of set-output
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hugo-site
          path: ./public  # Path to the built Hugo site

  deploy-content:

    needs: build  # Wait for the build job to finish
    runs-on: ubuntu-latest

    steps:

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: hugo-site
          path: ./public  # Download the build artifact

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure the Node version matches CDK requirements
      
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
  
      - name: Deploy site with Hugo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          hugo deploy