name: Deploy Infrastructure

on:
  push:

    paths:
      - 'infra/**'  # Trigger this workflow when changes occur in the CDK code
    branches:
      - master

jobs:

  deploy-infrastructure:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Ensure the Node version matches CDK requirements
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install AWS CDK Dependencies
        run: npm ci
          
      - name: Build Hugo Site
        run: | 
          hugo --minify

      - name: Deploy infra with CDK
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
        run: |
          npm run deploy
          