name: Update site content

on:

  workflow_run:
    workflows: ["Deploy Infrastructure"]  # This triggers after the infra workflow
    types:
      - completed
      
  push:

    paths:
      - 'content/**'
      - 'layouts/**'
      - 'assets/**'
      - 'config.toml'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      build-path: ${{ steps.build.outputs.build-path }}

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      # Check for infra changes on 'push' events
      - name: Check for infra changes
        id: infra_changes
        if: github.event_name == 'push'  # Only run this on 'push' events
        run: |
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^infra/'; then
            echo "infra-changes=true" >> $GITHUB_ENV
          else
            echo "infra-changes=false" >> $GITHUB_ENV

      # Stop the job if infra changes are detected
      - name: Stop workflow if infra is deploying
        if: github.event_name == 'push' && env.infra_changes == 'true'
        run: |
          echo "Infra deployment detected. Stopping content deployment."
          exit 0

      - name: Set up Hugo
        if: github.event_name != 'push' || env.infra_changes == 'false'  # Always run for 'workflow_run', conditionally for 'push'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        if: github.event_name != 'push' || env.infra_changes == 'false'  # Always run for 'workflow_run', conditionally for 'push'
        run: | 
          hugo --minify
          echo "build-path=$(pwd)/public" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hugo-site
          path: ./public  # Path to the built Hugo site

  deploy-content:

    needs: build  # Wait for the build job to finish
    runs-on: ubuntu-latest

    steps:

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: hugo-site
          path: ./public  # Download the build artifact

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure the Node version matches CDK requirements
      
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
  
      - name: Deploy site with Hugo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          hugo deploy